version: 2
workflows:
    single-simple:
        steps:
          - name: singlenode-single
            command: experiment.run_single_node
            paramsFile: .ps_project/param-file-experiment.yaml
            checks: #[optional]
                tensorflow:loss:
                    target: "0.0..0.5"
                    aggregate: "mean"
                defaults: #[optional]
                    precision: 3
        triggers:
            branches:
                only: .*
            tags:
                only:
                - v.*
                - latest
    hvd-multinode:
        steps:
          - name: "horovod-gradientci"
            command: experiment.run_mpi_multi_node
            paramsFile: .ps_project/horovod-multinode-mnist.yaml
        triggers:
            branches:
                only: .*
            tags:
                only:
                - v.*
                - latest
